%this function runs the sensor space analysis

function [] = sensor_space_analysis(eeg_data, XYTStats);

%Please provide:

%eeg_data- the file containing the preprocessed EEG data
%XYTStats- the output directory for the statistical inference

spm('defaults', 'EEG');
spm_jobman('initcfg');

clear matlabbatch

%Converting EEG preprocessed data to images

matlabbatch{1}.spm.meeg.images.convert2images.D = {eeg_data};
matlabbatch{1}.spm.meeg.images.convert2images.mode = 'scalp x time';
matlabbatch{1}.spm.meeg.images.convert2images.conditions = {};
matlabbatch{1}.spm.meeg.images.convert2images.channels{1}.type = 'EEG';
matlabbatch{1}.spm.meeg.images.convert2images.timewin = [-Inf Inf];
matlabbatch{1}.spm.meeg.images.convert2images.freqwin = [-Inf Inf];
matlabbatch{1}.spm.meeg.images.convert2images.prefix = '';

%Setting up the factorial design specification

matlabbatch{2}.spm.stats.factorial_design.dir = {XYTStats};
matlabbatch{2}.spm.stats.factorial_design.des.t2.scans1 = {
append(eeg_data,'_subject1\condition_Standard.nii,1')
append(eeg_data,'_subject1\condition_Standard.nii,2')
append(eeg_data,'_subject1\condition_Standard.nii,3')
append(eeg_data,'_subject1\condition_Standard.nii,4')
append(eeg_data,'_subject1\condition_Standard.nii,5')
append(eeg_data,'_subject1\condition_Standard.nii,6')
append(eeg_data,'_subject1\condition_Standard.nii,7')
append(eeg_data,'_subject1\condition_Standard.nii,8')
append(eeg_data,'_subject1\condition_Standard.nii,9')
append(eeg_data,'_subject1\condition_Standard.nii,10')
append(eeg_data,'_subject1\condition_Standard.nii,11')
append(eeg_data,'_subject1\condition_Standard.nii,12')
append(eeg_data,'_subject1\condition_Standard.nii,13')
append(eeg_data,'_subject1\condition_Standard.nii,14')
append(eeg_data,'_subject1\condition_Standard.nii,15')
append(eeg_data,'_subject1\condition_Standard.nii,16')
append(eeg_data,'_subject1\condition_Standard.nii,17')
append(eeg_data,'_subject1\condition_Standard.nii,18')
append(eeg_data,'_subject1\condition_Standard.nii,19')
append(eeg_data,'_subject1\condition_Standard.nii,20')
append(eeg_data,'_subject1\condition_Standard.nii,21')
append(eeg_data,'_subject1\condition_Standard.nii,22')
append(eeg_data,'_subject1\condition_Standard.nii,23')
append(eeg_data,'_subject1\condition_Standard.nii,24')
append(eeg_data,'_subject1\condition_Standard.nii,25')
append(eeg_data,'_subject1\condition_Standard.nii,26')
append(eeg_data,'_subject1\condition_Standard.nii,27')
append(eeg_data,'_subject1\condition_Standard.nii,28')
append(eeg_data,'_subject1\condition_Standard.nii,29')
append(eeg_data,'_subject1\condition_Standard.nii,30')
append(eeg_data,'_subject1\condition_Standard.nii,31')
append(eeg_data,'_subject1\condition_Standard.nii,32')
append(eeg_data,'_subject1\condition_Standard.nii,33')
append(eeg_data,'_subject1\condition_Standard.nii,34')
append(eeg_data,'_subject1\condition_Standard.nii,35')
append(eeg_data,'_subject1\condition_Standard.nii,36')
append(eeg_data,'_subject1\condition_Standard.nii,37')
append(eeg_data,'_subject1\condition_Standard.nii,38')
append(eeg_data,'_subject1\condition_Standard.nii,39')
append(eeg_data,'_subject1\condition_Standard.nii,40')
append(eeg_data,'_subject1\condition_Standard.nii,41')
append(eeg_data,'_subject1\condition_Standard.nii,42')
append(eeg_data,'_subject1\condition_Standard.nii,43')
append(eeg_data,'_subject1\condition_Standard.nii,44')
append(eeg_data,'_subject1\condition_Standard.nii,45')
append(eeg_data,'_subject1\condition_Standard.nii,46')
append(eeg_data,'_subject1\condition_Standard.nii,47')
append(eeg_data,'_subject1\condition_Standard.nii,48')
append(eeg_data,'_subject1\condition_Standard.nii,49')
append(eeg_data,'_subject1\condition_Standard.nii,50')
append(eeg_data,'_subject1\condition_Standard.nii,51')
append(eeg_data,'_subject1\condition_Standard.nii,52')
append(eeg_data,'_subject1\condition_Standard.nii,53')
append(eeg_data,'_subject1\condition_Standard.nii,54')
append(eeg_data,'_subject1\condition_Standard.nii,55')
append(eeg_data,'_subject1\condition_Standard.nii,56')
append(eeg_data,'_subject1\condition_Standard.nii,57')
append(eeg_data,'_subject1\condition_Standard.nii,58')
append(eeg_data,'_subject1\condition_Standard.nii,59')
append(eeg_data,'_subject1\condition_Standard.nii,60')
append(eeg_data,'_subject1\condition_Standard.nii,61')
append(eeg_data,'_subject1\condition_Standard.nii,62')
append(eeg_data,'_subject1\condition_Standard.nii,63')
append(eeg_data,'_subject1\condition_Standard.nii,64')
append(eeg_data,'_subject1\condition_Standard.nii,65')
append(eeg_data,'_subject1\condition_Standard.nii,66')
append(eeg_data,'_subject1\condition_Standard.nii,67')
append(eeg_data,'_subject1\condition_Standard.nii,68')
append(eeg_data,'_subject1\condition_Standard.nii,69')
append(eeg_data,'_subject1\condition_Standard.nii,70')
append(eeg_data,'_subject1\condition_Standard.nii,71')
append(eeg_data,'_subject1\condition_Standard.nii,72')
append(eeg_data,'_subject1\condition_Standard.nii,73')
append(eeg_data,'_subject1\condition_Standard.nii,74')
append(eeg_data,'_subject1\condition_Standard.nii,75')
append(eeg_data,'_subject1\condition_Standard.nii,76')
append(eeg_data,'_subject1\condition_Standard.nii,77')
append(eeg_data,'_subject1\condition_Standard.nii,78')
append(eeg_data,'_subject1\condition_Standard.nii,79')
append(eeg_data,'_subject1\condition_Standard.nii,80')
append(eeg_data,'_subject1\condition_Standard.nii,81')
append(eeg_data,'_subject1\condition_Standard.nii,82')
append(eeg_data,'_subject1\condition_Standard.nii,83')
append(eeg_data,'_subject1\condition_Standard.nii,84')
append(eeg_data,'_subject1\condition_Standard.nii,85')
append(eeg_data,'_subject1\condition_Standard.nii,86')
append(eeg_data,'_subject1\condition_Standard.nii,87')
append(eeg_data,'_subject1\condition_Standard.nii,88')
append(eeg_data,'_subject1\condition_Standard.nii,89')
append(eeg_data,'_subject1\condition_Standard.nii,90')
append(eeg_data,'_subject1\condition_Standard.nii,91')
append(eeg_data,'_subject1\condition_Standard.nii,92')
append(eeg_data,'_subject1\condition_Standard.nii,93')
append(eeg_data,'_subject1\condition_Standard.nii,94')
append(eeg_data,'_subject1\condition_Standard.nii,95')
append(eeg_data,'_subject1\condition_Standard.nii,96')
append(eeg_data,'_subject1\condition_Standard.nii,97')
append(eeg_data,'_subject1\condition_Standard.nii,98')
append(eeg_data,'_subject1\condition_Standard.nii,99')
append(eeg_data,'_subject1\condition_Standard.nii,100')
append(eeg_data,'_subject1\condition_Standard.nii,101')
append(eeg_data,'_subject1\condition_Standard.nii,102')
append(eeg_data,'_subject1\condition_Standard.nii,103')
append(eeg_data,'_subject1\condition_Standard.nii,104')
append(eeg_data,'_subject1\condition_Standard.nii,105')
append(eeg_data,'_subject1\condition_Standard.nii,106')
append(eeg_data,'_subject1\condition_Standard.nii,107')
append(eeg_data,'_subject1\condition_Standard.nii,108')
append(eeg_data,'_subject1\condition_Standard.nii,109')
append(eeg_data,'_subject1\condition_Standard.nii,110')
append(eeg_data,'_subject1\condition_Standard.nii,111')
append(eeg_data,'_subject1\condition_Standard.nii,112')
append(eeg_data,'_subject1\condition_Standard.nii,113')
append(eeg_data,'_subject1\condition_Standard.nii,114')
append(eeg_data,'_subject1\condition_Standard.nii,115')
append(eeg_data,'_subject1\condition_Standard.nii,116')
append(eeg_data,'_subject1\condition_Standard.nii,117')
append(eeg_data,'_subject1\condition_Standard.nii,118')
append(eeg_data,'_subject1\condition_Standard.nii,119')
append(eeg_data,'_subject1\condition_Standard.nii,120')
append(eeg_data,'_subject1\condition_Standard.nii,121')
append(eeg_data,'_subject1\condition_Standard.nii,122')
append(eeg_data,'_subject1\condition_Standard.nii,123')
append(eeg_data,'_subject1\condition_Standard.nii,124')
append(eeg_data,'_subject1\condition_Standard.nii,125')
append(eeg_data,'_subject1\condition_Standard.nii,126')
append(eeg_data,'_subject1\condition_Standard.nii,127')
append(eeg_data,'_subject1\condition_Standard.nii,128')
append(eeg_data,'_subject1\condition_Standard.nii,129')
append(eeg_data,'_subject1\condition_Standard.nii,130')
append(eeg_data,'_subject1\condition_Standard.nii,131')
append(eeg_data,'_subject1\condition_Standard.nii,132')
append(eeg_data,'_subject1\condition_Standard.nii,133')
append(eeg_data,'_subject1\condition_Standard.nii,134')
append(eeg_data,'_subject1\condition_Standard.nii,135')
append(eeg_data,'_subject1\condition_Standard.nii,136')
append(eeg_data,'_subject1\condition_Standard.nii,137')
append(eeg_data,'_subject1\condition_Standard.nii,138')
append(eeg_data,'_subject1\condition_Standard.nii,139')
append(eeg_data,'_subject1\condition_Standard.nii,140')
append(eeg_data,'_subject1\condition_Standard.nii,141')
append(eeg_data,'_subject1\condition_Standard.nii,142')
append(eeg_data,'_subject1\condition_Standard.nii,143')
append(eeg_data,'_subject1\condition_Standard.nii,144')
append(eeg_data,'_subject1\condition_Standard.nii,145')
append(eeg_data,'_subject1\condition_Standard.nii,146')
append(eeg_data,'_subject1\condition_Standard.nii,147')
append(eeg_data,'_subject1\condition_Standard.nii,148')
append(eeg_data,'_subject1\condition_Standard.nii,149')
append(eeg_data,'_subject1\condition_Standard.nii,150')
append(eeg_data,'_subject1\condition_Standard.nii,151')
append(eeg_data,'_subject1\condition_Standard.nii,152')
append(eeg_data,'_subject1\condition_Standard.nii,153')
append(eeg_data,'_subject1\condition_Standard.nii,154')
append(eeg_data,'_subject1\condition_Standard.nii,155')
append(eeg_data,'_subject1\condition_Standard.nii,156')
append(eeg_data,'_subject1\condition_Standard.nii,157')
append(eeg_data,'_subject1\condition_Standard.nii,158')
append(eeg_data,'_subject1\condition_Standard.nii,159')
append(eeg_data,'_subject1\condition_Standard.nii,160')
append(eeg_data,'_subject1\condition_Standard.nii,161')
append(eeg_data,'_subject1\condition_Standard.nii,162')
append(eeg_data,'_subject1\condition_Standard.nii,163')
append(eeg_data,'_subject1\condition_Standard.nii,164')
append(eeg_data,'_subject1\condition_Standard.nii,165')
append(eeg_data,'_subject1\condition_Standard.nii,166')
append(eeg_data,'_subject1\condition_Standard.nii,167')
append(eeg_data,'_subject1\condition_Standard.nii,168')
append(eeg_data,'_subject1\condition_Standard.nii,169')
append(eeg_data,'_subject1\condition_Standard.nii,170')
append(eeg_data,'_subject1\condition_Standard.nii,171')
append(eeg_data,'_subject1\condition_Standard.nii,172')
append(eeg_data,'_subject1\condition_Standard.nii,173')
append(eeg_data,'_subject1\condition_Standard.nii,174')
append(eeg_data,'_subject1\condition_Standard.nii,175')
append(eeg_data,'_subject1\condition_Standard.nii,176')
append(eeg_data,'_subject1\condition_Standard.nii,177')
append(eeg_data,'_subject1\condition_Standard.nii,178')
append(eeg_data,'_subject1\condition_Standard.nii,179')
append(eeg_data,'_subject1\condition_Standard.nii,180')
append(eeg_data,'_subject1\condition_Standard.nii,181')
append(eeg_data,'_subject1\condition_Standard.nii,182')
append(eeg_data,'_subject1\condition_Standard.nii,183')
append(eeg_data,'_subject1\condition_Standard.nii,184')
append(eeg_data,'_subject1\condition_Standard.nii,185')
append(eeg_data,'_subject1\condition_Standard.nii,186')
append(eeg_data,'_subject1\condition_Standard.nii,187')
append(eeg_data,'_subject1\condition_Standard.nii,188')
append(eeg_data,'_subject1\condition_Standard.nii,189')
append(eeg_data,'_subject1\condition_Standard.nii,190')
append(eeg_data,'_subject1\condition_Standard.nii,191')
append(eeg_data,'_subject1\condition_Standard.nii,192')
append(eeg_data,'_subject1\condition_Standard.nii,193')
append(eeg_data,'_subject1\condition_Standard.nii,194')
append(eeg_data,'_subject1\condition_Standard.nii,195')
append(eeg_data,'_subject1\condition_Standard.nii,196')
append(eeg_data,'_subject1\condition_Standard.nii,197')
append(eeg_data,'_subject1\condition_Standard.nii,198')
append(eeg_data,'_subject1\condition_Standard.nii,199')
append(eeg_data,'_subject1\condition_Standard.nii,200')
append(eeg_data,'_subject1\condition_Standard.nii,201')
append(eeg_data,'_subject1\condition_Standard.nii,202')
append(eeg_data,'_subject1\condition_Standard.nii,203')
append(eeg_data,'_subject1\condition_Standard.nii,204')
append(eeg_data,'_subject1\condition_Standard.nii,205')
append(eeg_data,'_subject1\condition_Standard.nii,206')
append(eeg_data,'_subject1\condition_Standard.nii,207')
append(eeg_data,'_subject1\condition_Standard.nii,208')
append(eeg_data,'_subject1\condition_Standard.nii,209')
append(eeg_data,'_subject1\condition_Standard.nii,210')
append(eeg_data,'_subject1\condition_Standard.nii,211')
append(eeg_data,'_subject1\condition_Standard.nii,212')
append(eeg_data,'_subject1\condition_Standard.nii,213')
append(eeg_data,'_subject1\condition_Standard.nii,214')
append(eeg_data,'_subject1\condition_Standard.nii,215')
append(eeg_data,'_subject1\condition_Standard.nii,216')
append(eeg_data,'_subject1\condition_Standard.nii,217')
append(eeg_data,'_subject1\condition_Standard.nii,218')
append(eeg_data,'_subject1\condition_Standard.nii,219')
append(eeg_data,'_subject1\condition_Standard.nii,220')
append(eeg_data,'_subject1\condition_Standard.nii,221')
append(eeg_data,'_subject1\condition_Standard.nii,222')
append(eeg_data,'_subject1\condition_Standard.nii,223')
append(eeg_data,'_subject1\condition_Standard.nii,224')
append(eeg_data,'_subject1\condition_Standard.nii,225')
append(eeg_data,'_subject1\condition_Standard.nii,226')
append(eeg_data,'_subject1\condition_Standard.nii,227')
append(eeg_data,'_subject1\condition_Standard.nii,228')
append(eeg_data,'_subject1\condition_Standard.nii,229')
append(eeg_data,'_subject1\condition_Standard.nii,230')
append(eeg_data,'_subject1\condition_Standard.nii,231')
append(eeg_data,'_subject1\condition_Standard.nii,232')
append(eeg_data,'_subject1\condition_Standard.nii,233')
append(eeg_data,'_subject1\condition_Standard.nii,234')
append(eeg_data,'_subject1\condition_Standard.nii,235')
append(eeg_data,'_subject1\condition_Standard.nii,236')
append(eeg_data,'_subject1\condition_Standard.nii,237')
append(eeg_data,'_subject1\condition_Standard.nii,238')
append(eeg_data,'_subject1\condition_Standard.nii,239')
append(eeg_data,'_subject1\condition_Standard.nii,240')
append(eeg_data,'_subject1\condition_Standard.nii,241')
append(eeg_data,'_subject1\condition_Standard.nii,242')
append(eeg_data,'_subject1\condition_Standard.nii,243')
append(eeg_data,'_subject1\condition_Standard.nii,244')
append(eeg_data,'_subject1\condition_Standard.nii,245')
append(eeg_data,'_subject1\condition_Standard.nii,246')
append(eeg_data,'_subject1\condition_Standard.nii,247')
append(eeg_data,'_subject1\condition_Standard.nii,248')
append(eeg_data,'_subject1\condition_Standard.nii,249')
append(eeg_data,'_subject1\condition_Standard.nii,250')
append(eeg_data,'_subject1\condition_Standard.nii,251')
append(eeg_data,'_subject1\condition_Standard.nii,252')
append(eeg_data,'_subject1\condition_Standard.nii,253')
append(eeg_data,'_subject1\condition_Standard.nii,254')
append(eeg_data,'_subject1\condition_Standard.nii,255')
append(eeg_data,'_subject1\condition_Standard.nii,256')
append(eeg_data,'_subject1\condition_Standard.nii,257')
append(eeg_data,'_subject1\condition_Standard.nii,258')
append(eeg_data,'_subject1\condition_Standard.nii,259')
append(eeg_data,'_subject1\condition_Standard.nii,260')
append(eeg_data,'_subject1\condition_Standard.nii,261')
append(eeg_data,'_subject1\condition_Standard.nii,262')
append(eeg_data,'_subject1\condition_Standard.nii,263')
append(eeg_data,'_subject1\condition_Standard.nii,264')
append(eeg_data,'_subject1\condition_Standard.nii,265')
append(eeg_data,'_subject1\condition_Standard.nii,266')
append(eeg_data,'_subject1\condition_Standard.nii,267')
append(eeg_data,'_subject1\condition_Standard.nii,268')
append(eeg_data,'_subject1\condition_Standard.nii,269')
append(eeg_data,'_subject1\condition_Standard.nii,270')
append(eeg_data,'_subject1\condition_Standard.nii,271')
append(eeg_data,'_subject1\condition_Standard.nii,272')
append(eeg_data,'_subject1\condition_Standard.nii,273')
append(eeg_data,'_subject1\condition_Standard.nii,274')
append(eeg_data,'_subject1\condition_Standard.nii,275')
append(eeg_data,'_subject1\condition_Standard.nii,276')
append(eeg_data,'_subject1\condition_Standard.nii,277')
append(eeg_data,'_subject1\condition_Standard.nii,278')
append(eeg_data,'_subject1\condition_Standard.nii,279')
append(eeg_data,'_subject1\condition_Standard.nii,280')
append(eeg_data,'_subject1\condition_Standard.nii,281')
append(eeg_data,'_subject1\condition_Standard.nii,282')
append(eeg_data,'_subject1\condition_Standard.nii,283')
append(eeg_data,'_subject1\condition_Standard.nii,284')
append(eeg_data,'_subject1\condition_Standard.nii,285')
append(eeg_data,'_subject1\condition_Standard.nii,286')
append(eeg_data,'_subject1\condition_Standard.nii,287')
append(eeg_data,'_subject1\condition_Standard.nii,288')
append(eeg_data,'_subject1\condition_Standard.nii,289')
append(eeg_data,'_subject1\condition_Standard.nii,290')
append(eeg_data,'_subject1\condition_Standard.nii,291')
append(eeg_data,'_subject1\condition_Standard.nii,292')
append(eeg_data,'_subject1\condition_Standard.nii,293')
append(eeg_data,'_subject1\condition_Standard.nii,294')
append(eeg_data,'_subject1\condition_Standard.nii,295')
append(eeg_data,'_subject1\condition_Standard.nii,296')
append(eeg_data,'_subject1\condition_Standard.nii,297')
append(eeg_data,'_subject1\condition_Standard.nii,298')
append(eeg_data,'_subject1\condition_Standard.nii,299')
append(eeg_data,'_subject1\condition_Standard.nii,300')
append(eeg_data,'_subject1\condition_Standard.nii,301')
append(eeg_data,'_subject1\condition_Standard.nii,302')
append(eeg_data,'_subject1\condition_Standard.nii,303')
append(eeg_data,'_subject1\condition_Standard.nii,304')
append(eeg_data,'_subject1\condition_Standard.nii,305')
append(eeg_data,'_subject1\condition_Standard.nii,306')
append(eeg_data,'_subject1\condition_Standard.nii,307')
append(eeg_data,'_subject1\condition_Standard.nii,308')
append(eeg_data,'_subject1\condition_Standard.nii,309')
append(eeg_data,'_subject1\condition_Standard.nii,310')
append(eeg_data,'_subject1\condition_Standard.nii,311')
append(eeg_data,'_subject1\condition_Standard.nii,312')
append(eeg_data,'_subject1\condition_Standard.nii,313')
append(eeg_data,'_subject1\condition_Standard.nii,314')
append(eeg_data,'_subject1\condition_Standard.nii,315')
append(eeg_data,'_subject1\condition_Standard.nii,316')
append(eeg_data,'_subject1\condition_Standard.nii,317')
append(eeg_data,'_subject1\condition_Standard.nii,318')
append(eeg_data,'_subject1\condition_Standard.nii,319')
append(eeg_data,'_subject1\condition_Standard.nii,320')
append(eeg_data,'_subject1\condition_Standard.nii,321')
append(eeg_data,'_subject1\condition_Standard.nii,322')
append(eeg_data,'_subject1\condition_Standard.nii,323')
append(eeg_data,'_subject1\condition_Standard.nii,324')
append(eeg_data,'_subject1\condition_Standard.nii,325')
append(eeg_data,'_subject1\condition_Standard.nii,326')
append(eeg_data,'_subject1\condition_Standard.nii,327')
append(eeg_data,'_subject1\condition_Standard.nii,328')
append(eeg_data,'_subject1\condition_Standard.nii,329')
append(eeg_data,'_subject1\condition_Standard.nii,330')
append(eeg_data,'_subject1\condition_Standard.nii,331')
append(eeg_data,'_subject1\condition_Standard.nii,332')
append(eeg_data,'_subject1\condition_Standard.nii,333')
append(eeg_data,'_subject1\condition_Standard.nii,334')
append(eeg_data,'_subject1\condition_Standard.nii,335')
append(eeg_data,'_subject1\condition_Standard.nii,336')
append(eeg_data,'_subject1\condition_Standard.nii,337')
append(eeg_data,'_subject1\condition_Standard.nii,338')
append(eeg_data,'_subject1\condition_Standard.nii,339')
append(eeg_data,'_subject1\condition_Standard.nii,340')
append(eeg_data,'_subject1\condition_Standard.nii,341')
append(eeg_data,'_subject1\condition_Standard.nii,342')
append(eeg_data,'_subject1\condition_Standard.nii,343')
append(eeg_data,'_subject1\condition_Standard.nii,344')
append(eeg_data,'_subject1\condition_Standard.nii,345')
append(eeg_data,'_subject1\condition_Standard.nii,346')
append(eeg_data,'_subject1\condition_Standard.nii,347')
append(eeg_data,'_subject1\condition_Standard.nii,348')
append(eeg_data,'_subject1\condition_Standard.nii,349')
append(eeg_data,'_subject1\condition_Standard.nii,350')
append(eeg_data,'_subject1\condition_Standard.nii,351')
append(eeg_data,'_subject1\condition_Standard.nii,352')
append(eeg_data,'_subject1\condition_Standard.nii,353')
append(eeg_data,'_subject1\condition_Standard.nii,354')
append(eeg_data,'_subject1\condition_Standard.nii,355')
append(eeg_data,'_subject1\condition_Standard.nii,356')
append(eeg_data,'_subject1\condition_Standard.nii,357')
append(eeg_data,'_subject1\condition_Standard.nii,358')
append(eeg_data,'_subject1\condition_Standard.nii,359')
append(eeg_data,'_subject1\condition_Standard.nii,360')
append(eeg_data,'_subject1\condition_Standard.nii,361')
append(eeg_data,'_subject1\condition_Standard.nii,362')
append(eeg_data,'_subject1\condition_Standard.nii,363')
append(eeg_data,'_subject1\condition_Standard.nii,364')
append(eeg_data,'_subject1\condition_Standard.nii,365')
append(eeg_data,'_subject1\condition_Standard.nii,366')
append(eeg_data,'_subject1\condition_Standard.nii,367')
append(eeg_data,'_subject1\condition_Standard.nii,368')
append(eeg_data,'_subject1\condition_Standard.nii,369')
append(eeg_data,'_subject1\condition_Standard.nii,370')
append(eeg_data,'_subject1\condition_Standard.nii,371')
append(eeg_data,'_subject1\condition_Standard.nii,372')
append(eeg_data,'_subject1\condition_Standard.nii,373')
append(eeg_data,'_subject1\condition_Standard.nii,374')
append(eeg_data,'_subject1\condition_Standard.nii,375')
append(eeg_data,'_subject1\condition_Standard.nii,376')
append(eeg_data,'_subject1\condition_Standard.nii,377')
append(eeg_data,'_subject1\condition_Standard.nii,378')
append(eeg_data,'_subject1\condition_Standard.nii,379')
append(eeg_data,'_subject1\condition_Standard.nii,380')
append(eeg_data,'_subject1\condition_Standard.nii,381')
append(eeg_data,'_subject1\condition_Standard.nii,382')
append(eeg_data,'_subject1\condition_Standard.nii,383')
append(eeg_data,'_subject1\condition_Standard.nii,384')
append(eeg_data,'_subject1\condition_Standard.nii,385')
append(eeg_data,'_subject1\condition_Standard.nii,386')
append(eeg_data,'_subject1\condition_Standard.nii,387')
append(eeg_data,'_subject1\condition_Standard.nii,388')
append(eeg_data,'_subject1\condition_Standard.nii,389')
append(eeg_data,'_subject1\condition_Standard.nii,390')
append(eeg_data,'_subject1\condition_Standard.nii,391')
append(eeg_data,'_subject1\condition_Standard.nii,392')
append(eeg_data,'_subject1\condition_Standard.nii,393')
append(eeg_data,'_subject1\condition_Standard.nii,394')
append(eeg_data,'_subject1\condition_Standard.nii,395')
append(eeg_data,'_subject1\condition_Standard.nii,396')
append(eeg_data,'_subject1\condition_Standard.nii,397')
append(eeg_data,'_subject1\condition_Standard.nii,398')
append(eeg_data,'_subject1\condition_Standard.nii,399')
append(eeg_data,'_subject1\condition_Standard.nii,400')
append(eeg_data,'_subject1\condition_Standard.nii,401')
append(eeg_data,'_subject1\condition_Standard.nii,402')
append(eeg_data,'_subject1\condition_Standard.nii,403')
append(eeg_data,'_subject1\condition_Standard.nii,404')
append(eeg_data,'_subject1\condition_Standard.nii,405')
append(eeg_data,'_subject1\condition_Standard.nii,406')
append(eeg_data,'_subject1\condition_Standard.nii,407')
append(eeg_data,'_subject1\condition_Standard.nii,408')
append(eeg_data,'_subject1\condition_Standard.nii,409')
append(eeg_data,'_subject1\condition_Standard.nii,410')
append(eeg_data,'_subject1\condition_Standard.nii,411')
append(eeg_data,'_subject1\condition_Standard.nii,412')
append(eeg_data,'_subject1\condition_Standard.nii,413')
append(eeg_data,'_subject1\condition_Standard.nii,414')
append(eeg_data,'_subject1\condition_Standard.nii,415')
};
%%
%%
matlabbatch{2}.spm.stats.factorial_design.des.t2.scans2 = {
append(eeg_data,'_subject1\condition_rare.nii,1')
append(eeg_data,'_subject1\condition_rare.nii,2')
append(eeg_data,'_subject1\condition_rare.nii,3')
append(eeg_data,'_subject1\condition_rare.nii,4')
append(eeg_data,'_subject1\condition_rare.nii,5')
append(eeg_data,'_subject1\condition_rare.nii,6')
append(eeg_data,'_subject1\condition_rare.nii,7')
append(eeg_data,'_subject1\condition_rare.nii,8')
append(eeg_data,'_subject1\condition_rare.nii,9')
append(eeg_data,'_subject1\condition_rare.nii,10')
append(eeg_data,'_subject1\condition_rare.nii,11')
append(eeg_data,'_subject1\condition_rare.nii,12')
append(eeg_data,'_subject1\condition_rare.nii,13')
append(eeg_data,'_subject1\condition_rare.nii,14')
append(eeg_data,'_subject1\condition_rare.nii,15')
append(eeg_data,'_subject1\condition_rare.nii,16')
append(eeg_data,'_subject1\condition_rare.nii,17')
append(eeg_data,'_subject1\condition_rare.nii,18')
append(eeg_data,'_subject1\condition_rare.nii,19')
append(eeg_data,'_subject1\condition_rare.nii,20')
append(eeg_data,'_subject1\condition_rare.nii,21')
append(eeg_data,'_subject1\condition_rare.nii,22')
append(eeg_data,'_subject1\condition_rare.nii,23')
append(eeg_data,'_subject1\condition_rare.nii,24')
append(eeg_data,'_subject1\condition_rare.nii,25')
append(eeg_data,'_subject1\condition_rare.nii,26')
append(eeg_data,'_subject1\condition_rare.nii,27')
append(eeg_data,'_subject1\condition_rare.nii,28')
append(eeg_data,'_subject1\condition_rare.nii,29')
append(eeg_data,'_subject1\condition_rare.nii,30')
append(eeg_data,'_subject1\condition_rare.nii,31')
append(eeg_data,'_subject1\condition_rare.nii,32')
append(eeg_data,'_subject1\condition_rare.nii,33')
append(eeg_data,'_subject1\condition_rare.nii,34')
append(eeg_data,'_subject1\condition_rare.nii,35')
append(eeg_data,'_subject1\condition_rare.nii,36')
append(eeg_data,'_subject1\condition_rare.nii,37')
append(eeg_data,'_subject1\condition_rare.nii,38')
append(eeg_data,'_subject1\condition_rare.nii,39')
append(eeg_data,'_subject1\condition_rare.nii,40')
append(eeg_data,'_subject1\condition_rare.nii,41')
append(eeg_data,'_subject1\condition_rare.nii,42')
append(eeg_data,'_subject1\condition_rare.nii,43')
append(eeg_data,'_subject1\condition_rare.nii,44')
append(eeg_data,'_subject1\condition_rare.nii,45')
append(eeg_data,'_subject1\condition_rare.nii,46')
append(eeg_data,'_subject1\condition_rare.nii,47')
append(eeg_data,'_subject1\condition_rare.nii,48')
append(eeg_data,'_subject1\condition_rare.nii,49')
append(eeg_data,'_subject1\condition_rare.nii,50')
append(eeg_data,'_subject1\condition_rare.nii,51')
append(eeg_data,'_subject1\condition_rare.nii,52')
append(eeg_data,'_subject1\condition_rare.nii,53')
append(eeg_data,'_subject1\condition_rare.nii,54')
append(eeg_data,'_subject1\condition_rare.nii,55')
append(eeg_data,'_subject1\condition_rare.nii,56')
append(eeg_data,'_subject1\condition_rare.nii,57')
append(eeg_data,'_subject1\condition_rare.nii,58')
append(eeg_data,'_subject1\condition_rare.nii,59')
append(eeg_data,'_subject1\condition_rare.nii,60')
append(eeg_data,'_subject1\condition_rare.nii,61')
append(eeg_data,'_subject1\condition_rare.nii,62')
append(eeg_data,'_subject1\condition_rare.nii,63')
append(eeg_data,'_subject1\condition_rare.nii,64')
append(eeg_data,'_subject1\condition_rare.nii,65')
append(eeg_data,'_subject1\condition_rare.nii,66')
append(eeg_data,'_subject1\condition_rare.nii,67')
append(eeg_data,'_subject1\condition_rare.nii,68')
append(eeg_data,'_subject1\condition_rare.nii,69')
append(eeg_data,'_subject1\condition_rare.nii,70')
append(eeg_data,'_subject1\condition_rare.nii,71')
append(eeg_data,'_subject1\condition_rare.nii,72')
append(eeg_data,'_subject1\condition_rare.nii,73')
append(eeg_data,'_subject1\condition_rare.nii,74')
append(eeg_data,'_subject1\condition_rare.nii,75')
append(eeg_data,'_subject1\condition_rare.nii,76')
append(eeg_data,'_subject1\condition_rare.nii,77')
append(eeg_data,'_subject1\condition_rare.nii,78')
append(eeg_data,'_subject1\condition_rare.nii,79')
append(eeg_data,'_subject1\condition_rare.nii,80')
append(eeg_data,'_subject1\condition_rare.nii,81')
append(eeg_data,'_subject1\condition_rare.nii,82')
append(eeg_data,'_subject1\condition_rare.nii,83')
append(eeg_data,'_subject1\condition_rare.nii,84')
append(eeg_data,'_subject1\condition_rare.nii,85')
append(eeg_data,'_subject1\condition_rare.nii,86')
append(eeg_data,'_subject1\condition_rare.nii,87')
append(eeg_data,'_subject1\condition_rare.nii,88')
append(eeg_data,'_subject1\condition_rare.nii,89')
append(eeg_data,'_subject1\condition_rare.nii,90')
append(eeg_data,'_subject1\condition_rare.nii,91')
append(eeg_data,'_subject1\condition_rare.nii,92')
append(eeg_data,'_subject1\condition_rare.nii,93')
append(eeg_data,'_subject1\condition_rare.nii,94')
append(eeg_data,'_subject1\condition_rare.nii,95')
append(eeg_data,'_subject1\condition_rare.nii,96')
append(eeg_data,'_subject1\condition_rare.nii,97')
append(eeg_data,'_subject1\condition_rare.nii,98')
append(eeg_data,'_subject1\condition_rare.nii,99')
};
%%
matlabbatch{2}.spm.stats.factorial_design.des.t2.dept = 0;
matlabbatch{2}.spm.stats.factorial_design.des.t2.variance = 1;
matlabbatch{2}.spm.stats.factorial_design.des.t2.gmsca = 0;
matlabbatch{2}.spm.stats.factorial_design.des.t2.ancova = 0;
matlabbatch{2}.spm.stats.factorial_design.cov = struct('c', {}, 'cname', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{2}.spm.stats.factorial_design.multi_cov = struct('files', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{2}.spm.stats.factorial_design.masking.tm.tm_none = 1;
matlabbatch{2}.spm.stats.factorial_design.masking.im = 1;
matlabbatch{2}.spm.stats.factorial_design.masking.em = {''};
matlabbatch{2}.spm.stats.factorial_design.globalc.g_omit = 1;
matlabbatch{2}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = 1;
matlabbatch{2}.spm.stats.factorial_design.globalm.glonorm = 1;

%Setting up the model estimation

matlabbatch{3}.spm.stats.fmri_est.spmmat = '<UNDEFINED>';
matlabbatch{3}.spm.stats.fmri_est.write_residuals = 0;
matlabbatch{3}.spm.stats.fmri_est.method.Classical = 1;

%Setting up the contrast manager

matlabbatch{4}.spm.stats.con.spmmat = '<UNDEFINED>';
matlabbatch{4}.spm.stats.con.consess{1}.fcon.name = '<UNDEFINED>';
matlabbatch{4}.spm.stats.con.consess{1}.fcon.weights = '<UNDEFINED>';
matlabbatch{4}.spm.stats.con.consess{1}.fcon.sessrep = 'none';
matlabbatch{4}.spm.stats.con.consess{2}.fcon.name = '<UNDEFINED>';
matlabbatch{4}.spm.stats.con.consess{2}.fcon.weights = '<UNDEFINED>';
matlabbatch{4}.spm.stats.con.consess{2}.fcon.sessrep = 'none';
matlabbatch{4}.spm.stats.con.consess{3}.fcon.name = '<UNDEFINED>';
matlabbatch{4}.spm.stats.con.consess{3}.fcon.weights = '<UNDEFINED>';
matlabbatch{4}.spm.stats.con.consess{3}.fcon.sessrep = 'none';
matlabbatch{4}.spm.stats.con.consess{4}.tcon.name = '<UNDEFINED>';
matlabbatch{4}.spm.stats.con.consess{4}.tcon.weights = '<UNDEFINED>';
matlabbatch{4}.spm.stats.con.consess{4}.tcon.sessrep = 'none';
matlabbatch{4}.spm.stats.con.consess{5}.fcon.name = '<UNDEFINED>';
matlabbatch{4}.spm.stats.con.consess{5}.fcon.weights = '<UNDEFINED>';
matlabbatch{4}.spm.stats.con.consess{5}.fcon.sessrep = 'none';
matlabbatch{4}.spm.stats.con.delete = 0;

%Reporting the results

matlabbatch{5}.spm.stats.results.spmmat = '<UNDEFINED>';
matlabbatch{5}.spm.stats.results.conspec = struct('titlestr', {}, 'contrasts', {}, 'threshdesc', {}, 'thresh', {}, 'extent', {}, 'conjunction', {}, 'mask', {});
matlabbatch{5}.spm.stats.results.units = 1;
matlabbatch{5}.spm.stats.results.export{1}.ps = true;

spm('defaults', 'EEG');
spm_jobman('run', matlabbatch);
